### ISSUE TITLE
When will you release the code？

### ISSUE THREAD

**Issue by ImmortalSdm** [Vermeille/cfg-llm#1]
Looking forward to the release : )

**Comment by Vermeille** [comment]
CFG has been implemented in Hugging Face, llama.cpp and many other toolkits already :)

**Comment by ImmortalSdm** [comment]
Thanks for your reply~

**Comment by ImmortalSdm** [comment]
For anyone willing to try the CFG, I found the reply of author @Vermeille here: [https://github.com/turboderp/exllama/issues/129#issuecomment-1619265427](url)
